### ISSUE TITLE
Switch from Trait based to Generic struct

### ISSUE THREAD

**Issue by NattapongSiri** [NattapongSiri/torcher#18]
# Background
An implementation by using trait center approach usually end up with various language limitation.
For example:
- [Trait alias](https://github.com/rust-lang/rfcs/blob/master/text/1733-trait-alias.md).
- [ATC (Associate Type Construct)](https://github.com/rust-lang/rfcs/blob/master/text/1598-generic_associated_types.md)

Which make implementation goes very slow.
## Why we need that ?
It's because while trying to implement Tensor view. I don't want to create an entire unsafe trait. So I chose to create new struct named `TensorView`. I don't want to have concrete struct for every `Tensor` counterpart. That'd make code maintenance a nightmare. I chose to have `TensorView<T> where T: Tensor`. Here come the problem.
1. If I reuse `Tensor` trait directly, it'd have a lot of function that simply `panic!("Op is not support")`. For example `new()` function.
2. If I split `Tensor` trait to multiple traits then have `Tensor` trait extend all these trait, there'll a lot and lot of associate type. Take a look at 9463098aba37174b56057a02d4ce46a9eaca8dad where `Tensor` trait signature now look weird.
3. User cannot use `&Tensor` trait object due to [Trait alias issue](https://github.com/rust-lang/rfcs/blob/master/text/1733-trait-alias.md). User will need to specify `Datum`, `Storage`, and `Tensor` associate type for every super trait and all of it use the same name. I'm not even sure how to specify the same named associate type multiple times.
4. To overcome such issue, we may change signature of those super trait to generic instead of associate type. However, we will need either `Tensor<T> where T: Tensor` or in `Tensor` trait's where clause will need some `Self: Sized`. The `where Self: Sized` approach lead to `Tensor` cannot be used as trait object. The `Tensor<T>` approach will be a bit unexpected because each concrete struct will only implement only single datatype for Tensor. It's not generic and that's why we chose to use associate type in the first place. Another issue with `Tensor<T>` is `struct TensorView` will impossible to construct. It'll have signature like `struct TensorView<T, U> where T: Tensor<U>` and compiler will complain that `U` is not used. If we choose to eliminate `TensorView` struct and use `TensorView` trait instead, we will end up need [ATC](https://github.com/rust-lang/rfcs/blob/master/text/1598-generic_associated_types.md) because somewhere in implementation, there'll be 
```Rust
impl TensorView for SomeStruct {
    type for<U> Tensor: Tensor<U>; // Currently compile error
    // all other view functions 
}
``` 
This is because using generic TensorView trait will end up with the same compile error like struct like this `impl<T, U> TensorView<T> for SomeStruct where T: Tensor<U>` and compiler will complain that U is not used.
# Solution
Get rid of all those traits and use generic struct for Tensor instead. The problem to solve is Caffe2 use different function name for different datatype. To solve issue:
1. We may still need to rely on build script mechanism to generate impl<T> for each datatype and map those function to correct Caffe2 function. 
2. We may choose to use proc_macro_derive to solve such issue because Caffe2 has fix template for every function. Therefore, we can make derive macro taking optional string and use that string to convert each function name to Caffe2 function.

This will workaround the issue of unable to use Tensor trait object by user able to take single generic struct as parameter.

# TODO
- [x] Implement generic storage struct (Done in 71798ba)
- [x] Implement storage functionality (Done in 71798ba)
- [ ] Implement generic tensor struct
- [ ] Implement tensor create op
- [ ] Implement tensor reshape op
- [ ] Implement tensor data manipulate op
- [ ] Implement tensor view op

**Comment by NattapongSiri** [comment]
The problem with generic struct approach is that each concrete struct need different Drop implementation because the allocated storage is in Caffe2 and each free function have different name.
Rust, however, don't permit this. This is because Drop trait has no generic. Rust, therefore, complain that Drop is implemented multiple times.
For example:
```Rust
struct Storage<T> {data: T}
trait StorageOp<T> {fn do_something(&self) -> T;}
impl StorageOp<u8> for Storage<u8> {fn do_something(&self) -> u8 {self.data}}
impl StorageOp<f32> for Storage<f32> {fn do_something(&self) -> f32 {self.data}}
impl Drop for Storage<u8> {
    fn drop(&mut self) {free_byte();}
}
impl Drop for Storage<f32> { // now compile error because 2 drop is implemented.
    fn drop(&mut self) {free_float();}
}
```
If we try to implement free inside StorageOp and attempt to implement Drop on generic T, we will end up with this error:
```Rust
trait StorageOp<T> {
    fn free(&mut self);
    // all other functions definition
}
impl StorageOp<u8> for Storage<u8> {
    fn free(mut self) {free_byte();}
    // all other functions
}
impl StorageOp<f32> for Storage<f32> {
    fn free(mut self) {free_float();}
    // all other functions
}
impl<T, U> Drop for T where T: StorageOp<U> { // compile error because U is unconstrained
    fn drop(&mut self) {
        self.free();
    }
}
```
To fix this, we probably need [ATC](https://github.com/rust-lang/rfcs/blob/master/text/1598-generic_associated_types.md) if it permit syntax like:
```Rust
impl<T> Drop for T where for<U> T: StorageOp<U> { 
    fn drop(&mut self) {
        self.free();
    }
}
```

**Comment by NattapongSiri** [comment]
By leveraging Rust nightly, Commit 71798ba successfully implement `Storage<T>` struct by using [specialization](https://github.com/rust-lang/rfcs/blob/master/text/1210-impl-specialization.md).
However, it doesn't seem like this functionality will be stable anytime soon.
