### ISSUE TITLE
Implement narrow view on tensor

### ISSUE THREAD

**Issue by NattapongSiri** [NattapongSiri/torcher#19]
# TODO
- [x] Add narrow function to ViewOp trait
- [x] Implement narrow on all supported tensor type.
- [x] Add convenient function/macro to let user easily manipulate view
- [x] Add test cases

**Comment by NattapongSiri** [comment]
Implement 2 narrow functionalities on both Tensor and TensorView.
1. `narrow` function that take `&[Range<usize>]`
2. `narrow_on` function that take `dim: usize, bound: Range<usize>`
The former is intended to be used in case where there when multiple narrow on multiple dimension in single op is required.
The later is intended to be used in case where user need to narrow on one of the dimension.

The advantage of `narrow` function is, it's fast. It perform narrow once for every dimension.
The disadvantage is, every dimensions need to have explicit bound defined in parameter.

The advantage of `narrow_on` function is, it's verbose and can be chained to have the similar shape tensor to `narrow` function. It is harder to mistake the shape on some specific dimension as `narrow` function need to know a new shape of tensor but this function need to know only the dimension that's going to get narrow down.
The disadvantage of `narrow_on` function is, it's single op on every chain of `narrow_on` call. So if user chain `narrow_on(0, 1..3)?.narrow_on(1, 2..5)?;` then it execute `narrow` op twice. 

# Example
## Explicit shape of target tensor
```Rust
let ts = FloatTensor::new_with_size_3d([4, 10, 6]);
ts.iter_mut().enumerate().for_each(|(i, v)| *v = i as f32);
// narrow down first two dimension in single op. The last range need to be specified because tensor has 3 dimensions
let view = narrow(&[1..3, 2..5, 0..5])?;
assert_eq!(view.shape(), &[2, 3, 5]);
```
## Implicit shape of target tensor
```Rust
fn sampling_tensor<T: Tensor>(t: T) -> TensorView<T> {
  // randomly generate usize value to variable `i`, `j` and check to ensure that `i` and `j` won't go out of bound.
  t.narrow_on(0, i..(i + 2)).unwrap() // first narrow op
   .narrow_on(1, j..(j + 3)).unwrap() // second narrow op
  // the return tensor will have first two dim of shape [2, 3] and all remaining dimension is untouched.
}
```
